name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-linux-i386:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build linux-i386
      run: |
        scripts/build-ubuntu-i386.sh
        zip -r build-linux-i386.zip build
    - uses: actions/upload-artifact@v2
      with:
        name: Source Engine - Linux 32-bit
        path: ./*.zip

  build-linux-amd64:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh
        zip -r build-linux-amd64.zip build
    - uses: actions/upload-artifact@v2
      with:
        name: Source Engine - Linux 64-bit
        path: ./*.zip

  build-android-armv7a:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build android-armv7a
      run: |
        scripts/build-android-armv7a.sh
        zip -r build-android-armv7a.zip build
    - uses: actions/upload-artifact@v2
      with:
        name: Source Engine - Android armv7a
        path: ./*.zip

  build-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug
        ./waf.bat build
        choco install zip
        zip -r build-windows-i386.zip build
    - uses: actions/upload-artifact@v2
      with:
        name: Source Engine - Windows 32-bit
        path: ./*.zip

  build-dedicated-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug -d
        ./waf.bat build

  build-dedicated-linux-i386:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated linux-i386
      run: |
        scripts/build-ubuntu-i386.sh -d

  build-dedicated-linux-amd64:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh -d
