name: Tests

on: [push, pull_request]

jobs:
  tests-linux-i386:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Run tests linux-i386
      run: |
        scripts/tests-ubuntu-i386.sh

  tests-linux-amd64:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Run tests linux-amd64
      run: |
        scripts/tests-ubuntu-amd64.sh

  tests-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Run tests windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release --tests --prefix=out/
        ./waf.bat install
        cd out
        $env:Path = "bin";
        ./unittest.exe

  tests-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Run tests windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release --tests --prefix=out/ -8
        ./waf.bat install
        cd out
        $env:Path = "bin";
        ./unittest.exe
